# Generated by Django 3.0.6 on 2020-05-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipping',
            name='kind_of_clipping',
            field=models.CharField(choices=[('Highlight', 'Highlight'), ('Note', 'Note'), ('Bookmark', 'Bookmark')], default='Highlight', max_length=10),
        ),
        migrations.AlterField(
            model_name='clipping',
            name='message',
            field=models.TextField(),
        ),
    ]
