# Generated by Django 3.0.6 on 2020-05-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_auto_20200517_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='number_of_book_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='number_of_clippings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='number_of_highlights',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='number_of_notes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.URLField(default=None),
        ),
    ]
