# Generated by Django 3.0.6 on 2020-05-19 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0003_auto_20200519_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='url',
        ),
        migrations.AddField(
            model_name='book',
            name='URL',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clipping',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shelf.Book', verbose_name='the related book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
