# Generated by Django 3.0.6 on 2020-05-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0005_auto_20200519_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipping',
            name='location',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
