# Generated by Django 3.0.6 on 2020-05-20 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0006_auto_20200519_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='number_of_book_marks',
        ),
        migrations.RemoveField(
            model_name='book',
            name='number_of_highlights',
        ),
        migrations.RemoveField(
            model_name='book',
            name='number_of_notes',
        ),
    ]
