# Generated by Django 3.0.6 on 2020-05-20 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0007_auto_20200520_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='number_of_clippings',
        ),
    ]
