# Generated by Django 3.0.6 on 2020-05-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0008_remove_book_number_of_clippings'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='exceeded_number_of_clippings',
            field=models.IntegerField(default=0),
        ),
    ]
