# Generated by Django 3.0.6 on 2020-05-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0010_auto_20200520_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='URL',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
