# Generated by Django 3.0.6 on 2020-05-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0012_auto_20200520_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='URL',
            new_name='imageURL',
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(null=True),
        ),
    ]
