# Generated by Django 3.0.6 on 2020-05-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0014_auto_20200523_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipping',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
