# Generated by Django 3.0.6 on 2020-05-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0015_auto_20200523_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipping',
            name='message',
            field=models.TextField(default='', unique=True),
        ),
    ]
